### ISSUE TITLE
Jobs queueing up in Categorizer Web UI

### ISSUE THREAD

**Issue by rickestrada** [bahuma20/firefly-iii-ai-categorize#2]
I followed guide to the letter, but I'm missing something I'm sure.
Besides creating the 'secret key' in the API page and applying it in the docker-compose file, anything else I may be missing? I have about $5 in my OpenAI account, but the API key's "last used" value is 'never'...
Please let me know what info I can share to help with troubleshooting!

![image](https://github.com/bahuma20/firefly-iii-ai-categorize/assets/31040010/8c7a2c2b-453a-4aa0-a5e5-ef95c7cfaa61)

![image](https://github.com/bahuma20/firefly-iii-ai-categorize/assets/31040010/4f194f83-9abc-4174-a890-54eadf733af8)

**Comment by bahuma20** [comment]
Can you see anything in the logs?
`docker-compose logs categorizer`

**Comment by rickestrada** [comment]
Jeez sorry I should have pulled logs... it's been a long day :)
OK ... so... I didn't change anything, just tried a job to pull real-time logs, and now the service looks like it's working. I imported a CSV with about 10 transactions and the ones with 'rules' worked OK, and the ones without 'rules', AI seemed to match pretty well.
Attached is the log output in case you see anything fishy, but I think maybe my server was busy when the queries failed.
Anyway, if I get failures in the future I will attach log output.
Thanks so much for working on this! It will make my life easier importing years of data from Mint into FF3.

[logs_20231129_181738_CST.txt](https://github.com/bahuma20/firefly-iii-ai-categorize/files/13506871/logs_20231129_181738_CST.txt)

**Comment by D4rkT1m0** [comment]
hello there,
i host a firefly docker on a Synology NAS, with 'Container Manager'
I also host the AI Categorizer on Docker, on the same NAS.
I can access to the web UI.
and I also encounter the same 'Not yet classified'

to see the logs, I use the Container Manager UI
here is an extract
```
2024/04/19   00:31:26,stdout,connected
--
 
2024/04/18 15:52:56,stdout,Job error   undefined undefined
 
2024/04/18 15:52:56,stdout,}
 
2024/04/18 15:52:56,stdout,  timeStamp: 579881558.9355102
 
2024/04/18 15:52:56,stdout,"  cancelable: false,
```

Does the solution is actually enabling the logs with the docker command (docker-compose logs categorizer) the key to make it work?
do you know how to do this on a Synology NAS?

I'm stcuk with a bunch of Not classified yet transaction

thank you for your time and answer
Guillaume

**Comment by D4rkT1m0** [comment]
Any answer guys?
